application: autoproxy2pac-alfa
version: 1
runtime: python
api_version: 1

handlers:
- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt
- url: /\.cron
  script: cron.py
  login: admin
- url: /admin.*
  script: $PYTHON_LIB/google/appengine/ext/admin
  login: admin
- url: .*
  script: main.py
