application: autoproxy2pac
version: 2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static
  secure: always
- url: /\.cron
  script: cron.py
  login: admin
- url: .*
  script: main.py
  secure: always
