application: autoproxy2pac
version: 2
runtime: python
api_version: 1

handlers:
- url: /pac/.*
  script: main.py
- url: /gfwtest.*
  script: gfwtest.py
- url: /changelog/.*
  script: changelog.py
- url: /static
  static_dir: static
- url: /\.cron
  script: cron.py
  login: admin
- url: .*
  script: main.py
